---
title: "SharksFishCoralDAG"
author: "Simon Dedman"
format: html
editor: visual
---

# Load data
```{r}
ReefWideBRUVUVC <-  readr::read_csv(file =  "/home/simon/Documents/Si Work/PostDoc Work/FIU/2024-01_SharksFishCoral-FrenchPoly/NFF Data code/ReefWideBRUVUVC.csv")
```
Between BRUV+UVC combined and running DAG, surely I need to get all other variables, do I have them all?

See https://docs.google.com/spreadsheets/d/1x7GLAVqXHQXAk9JVcsNAaS7aMi1AQ-DO/edit#gid=750764017

# DAG

## Setup & run DAG

See `?dagitty` for info on how to format this properly.

`x [exposure,pos="1,0"]`

```{r}
#| echo: false
remotes::install_github("jtextor/dagitty/r")
library(dagitty)
dagitty(x = "dag{
PctHardCoral [outcome,pos="-0.896,0.994"]
ApexSharks [pos="-0.613,-1.851"]
CoralRugosityArea [pos="-0.759,1.443"]
CrownOfThorns [latent,pos="-1.844,1.177"]
GrayReefSharks [exposure,pos="-1.389,-1.080"]
JuvenileSharks [latent,pos="-0.544,-1.044"]
LRovingPiscivores [outcome,pos="-0.309,-0.576"]
LSiWPiscivores [outcome,pos="-0.945,-0.604"]
LTeleostHerbivore [outcome,pos="-1.199,0.125"]
OffshorePrey [latent,pos="-1.795,-1.407"]
STeleostHerbivore [outcome,pos="-1.010,0.302"]
SeaTurtle [latent,pos="0.196,-0.511"]
BlacktipReefSharks [exposure,pos="-0.179,-1.248"]
IslandGeomorphology [pos="-2.023,1.611"]
NutrientRunOff [latent,pos="-1.586,1.381"]
SicklefinLemonSharks [pos="-1.213,-1.697"]
SmallBodiedSharks [pos="-1.470,-0.433"]
SmallPiscivores [outcome,pos="-0.617,-0.405"]
TeleostSpongivore [outcome,pos="-0.791,0.476"]
WhitetipReefSharks [pos="-1.962,-0.863"]
Coralivore [outcome,pos="-0.560,0.466"]
Grubbers [outcome,pos="-0.197,0.469"]
Invertivore [outcome,pos="-0.366,0.466"]
Macroalgae [pos="-1.595,0.792"]
cyclones [latent,pos="-1.187,1.608"]
depth [latent,pos="-2.106,-0.337"]
light [latent,pos="-1.739,-0.110"]
temperature [pos="-2.066,0.506"]
turbidity [pos="-2.102,0.071"]
ApexSharks -> GrayReefSharks
ApexSharks -> JuvenileSharks
ApexSharks -> LRovingPiscivores
ApexSharks -> LSiWPiscivores
ApexSharks -> BlacktipReefSharks
ApexSharks -> SmallBodiedSharks
CrownOfThorns -> PctHardCoral
CrownOfThorns -> CoralRugosityArea
GrayReefSharks -> STeleostHerbivore
GrayReefSharks -> SmallBodiedSharks
GrayReefSharks -> SmallPiscivores
GrayReefSharks -> TeleostSpongivore
GrayReefSharks -> Coralivore
GrayReefSharks -> Grubbers
GrayReefSharks -> Invertivore
GrayReefSharks <-> WhitetipReefSharks
LRovingPiscivores -> STeleostHerbivore
LRovingPiscivores -> SmallPiscivores
LRovingPiscivores -> TeleostSpongivore
LRovingPiscivores -> Coralivore
LRovingPiscivores -> Grubbers
LRovingPiscivores -> Invertivore
LSiWPiscivores -> STeleostHerbivore
LSiWPiscivores -> SmallPiscivores
LSiWPiscivores -> TeleostSpongivore
LSiWPiscivores -> Coralivore
LSiWPiscivores -> Grubbers
LSiWPiscivores -> Invertivore
OffshorePrey -> GrayReefSharks
BlacktipReefSharks -> STeleostHerbivore
BlacktipReefSharks -> SmallPiscivores
BlacktipReefSharks -> TeleostSpongivore
BlacktipReefSharks -> Coralivore
BlacktipReefSharks -> Grubbers
BlacktipReefSharks -> Invertivore
IslandGeomorphology -> NutrientRunOff
NutrientRunOff -> CrownOfThorns
NutrientRunOff -> Macroalgae
SicklefinLemonSharks -> GrayReefSharks
SicklefinLemonSharks -> JuvenileSharks
SicklefinLemonSharks -> LSiWPiscivores
SicklefinLemonSharks -> BlacktipReefSharks
SicklefinLemonSharks -> SmallBodiedSharks
Macroalgae -> PctHardCoral
cyclones -> CoralRugosityArea
depth -> light
light -> PctHardCoral
light -> Macroalgae
temperature -> PctHardCoral
temperature -> Macroalgae
turbidity -> light
}
",
layout = TRUE) # automatically generate layout coordinates for each variable (see graphLayout)
# Error: unexpected string constant in: PctHardCoral [outcome,pos="-0.896,0.994"]  Apex sharks [pos=""

```
